version: '3.3'
services:

  nginx_gateway:
    hostname: nginx_gateway
    container_name: nginx_gateway
    image: nginx:1.25.3
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Mount your custom Nginx configuration file
      - ./nginx/web:/usr/share/nginx/html
    networks:
      - app_network

  ##        PostgreSQL Database   ###
  postgres_db:
    hostname: postgres_db
    container_name: postgres_db
    image: postgres:14.10
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=moviedb
    networks:
      - app_network

  ##        Microservices   ###
  auth:
    hostname: movie-auth
    container_name: movie-auth
    image: movie_auth:dev
    restart: unless-stopped
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SERVER_PORT=80
      # application
      - APP_JWT-SECRET=ZmlsbVJhdGVBcHBTZWNyZXRLZXktZmlsbVJhdGVBcHBTZWNyZXRLZXktZmlsbVJhdGVBcHBTZWNyZXRLZXktZmlsbVJhdGVBcHBTZWNyZXRLZXk=
      # datasource
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/moviedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - '8080:80'
    networks:
     - app_network


  movie:
    hostname: movie
    container_name: movie
    image: movie:dev
    restart: unless-stopped
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SERVER_PORT=80
      # application
      - APP_JWT-SECRET=ZmlsbVJhdGVBcHBTZWNyZXRLZXktZmlsbVJhdGVBcHBTZWNyZXRLZXktZmlsbVJhdGVBcHBTZWNyZXRLZXktZmlsbVJhdGVBcHBTZWNyZXRLZXk=
      - app.movie.rate.host=http://movie-rate
      # datasource
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/moviedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - '8081:80'
    networks:
     - app_network

  rate:
    hostname: movie-rate
    container_name: movie-rate
    image: movie_rate:dev
    restart: unless-stopped
    depends_on:
      postgres_db:
        condition: service_healthy
    environment:
      - _JAVA_OPTIONS=-Xmx512m -Xms256m
      - SERVER_PORT=80
      # application
      - APP_JWT-SECRET=ZmlsbVJhdGVBcHBTZWNyZXRLZXktZmlsbVJhdGVBcHBTZWNyZXRLZXktZmlsbVJhdGVBcHBTZWNyZXRLZXktZmlsbVJhdGVBcHBTZWNyZXRLZXk=
      # datasource
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres_db:5432/moviedb
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    ports:
      - '8082:80'
    networks:
     - app_network

volumes:
  postgres:
    driver: local

networks:
  app_network:
    driver: bridge